#include "Commands.hpp"

namespace command
{

	int INIT_MAP = 10;
	int INIT_MATRIX_TRANSFER = 11;
	int ON_NEW_MATCH = 12;
	int ON_RESET_MATCH = 13;
	int ON_FINISH_MATCH = 14;

	int ON_ANIMATION_NEW_MATCH = 20;
	int ON_GAME_OVER = 21;

	int ON_TAP_ITEM = 401;
	int ON_MOVE_OVER_ITEM = 402;
	int ON_TOUCH_END_CANCEL_ITEM = 403;
	int ON_TAP_BACKGROUND = 404;


	int ON_GLOBAL_TAP = 405;
	int ON_GLOBAL_TOUCH_BEGIN = 406;
	int ON_GLOBAL_TOUCH_MOVE = 407;
	int ON_GLOBAL_TOUCH_END = 408;
	int ON_GLOBAL_FLING = 409;
	int ON_GLOBAL_ZOOM = 410;

	int ON_MOVE_GAME_CAMERA = 421;
	int ON_FLING_GAME_CAMERA = 422;
	int ON_ZOOM_CAMERA = 423;
	int ON_UNZOOM_CAMERA = 424;
	int STOP_FLING_GAME_CAMERA = 425;

	int MOVE_TROOP = 601;
	int ON_CLICK_GENERATE_CASTLE_HOUSE = 602;
	int REQUEST_MOVE_TROOP = 603;

	int SHOW_HUD_BUILD_TROOP = 801;
	int HIDE_HUD_BUILD_TROOP = 802;
	int RESET_HUD_TRANSFER = 803;
	int HUD_UPDATE_TROOP = 804;

	int ASK_HUD_TROOP_TRANSFER_CONFIG = 1001;
	int ASK_GAME_RESULT = 1002;
};


