#pragma once

#include "ActionComponent.hpp"
#include "AnimationComponent.hpp"
#include "AttackComponent.hpp"
#include "ConnectorComponent.hpp"
#include "HealthComponent.hpp"
#include "IDComponent.hpp"
#include "PlaySideComponent.hpp"
#include "PositionComponent.hpp"
#include "RemoveableComponent.hpp"
#include "RenderComponent.hpp"
#include "RenderSortableComponent.hpp"
#include "ScopeComponent.hpp"
#include "ShapeComponent.hpp"
#include "StateComponent.hpp"
#include "TargetComponent.hpp"
#include "TimeComponent.hpp"
#include "VelocityComponent.hpp"
#include "PathFollowComponent.hpp"
#include "TroopContainerComponent.hpp"
#include "BuilderComponent.hpp"
#include "TypeComponent.hpp"

